### PR TITLE
Add support for Rails 7

### PR DESCRIPTION
**Pull request by jazairi**
### Why these changes are being introduced:

This gem currently supports Rails 5 and 6 only, but we are starting
to write applications that use Rails 7.

### Relevant ticket(s):

https://github.com/MITLibraries/timdex-ui/issues/16

### How this addresses that need:

This updates the gemspec to support versions of Rails greater than
or equal to 5 but less than 8.

### Side effects of this change:

N/A.

### CODE REVIEW

**Comment by JPrevost** [comment]
@jazairi I suspect this is fine, but can you confirm that it still works properly locally with both Rails 6 and Rails 7 apps before we merge and release it? Hit me up on Slack if you want any tips on how to do that.

**Comment by jazairi** [comment]
@JPrevost Confirmed that this does work on Rails 6 and Rails 7 by bundling the gem from source locally with Bento and TIMDEX UI. As we discussed this morning, there's some additional config required in Rails 7, which I'll include in my PR to add the theme gem to TIMDEX UI.

Once thing I should mention is that the theme gem uses `sassc-rails` as a dependency, which we should move away from as it's unsupported as far as I know. All of the Rails 7 options I'm aware of (`dartsass`, `cssbundler`, etc.) require an installation step that I'm not sure how to complete in a Rails Engine. If you have any ideas on how to work around that, let me know. Otherwise, I'd support opening a ticket to investigate further, and merging this as is in the meantime with that risk noted in the commit message.

**Review by JPrevost — APPROVED** [review]
Please update the research ticket you noted in your comments so we don't forget to come back to that.

Can you also open ticket to add rails 7 layout features back to the layout template (I believe we'll lose Hotwire support if we use a Rails 6 app template but could be mistaken).

**Comment by jazairi** [comment]
@JPrevost 
SASS ticket: https://github.com/MITLibraries/mitlibraries-theme/issues/24
Layouts ticket: https://github.com/MITLibraries/mitlibraries-theme/issues/25

**Pull request merged**
